AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/simple_form.rb'


Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'it']
  Exclude:
    - 'config/environments/*.rb'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'
